package graph;

import org.jgrapht.graph.DefaultWeightedEdge;
import org.jgrapht.graph.Pseudograph;

public class Via {
    public static Pseudograph <String, DefaultWeightedEdge> via () {
        Pseudograph <String, DefaultWeightedEdge> graph = new Pseudograph <> (DefaultWeightedEdge.class);

        // TODO Halifax - Sydney - Montreal : 340 km
        graphUtils.addEdge(graph, "Halifax", "Armdale", 6.0);
        graphUtils.addEdge(graph, "Armdale", "Rockingham", 4.0);
        graphUtils.addEdge(graph, "Rockingham", "Bedford", 7.0);
        graphUtils.addEdge(graph, "Bedford", "Windsor Junction", 8.0);
        graphUtils.addEdge(graph, "Windsor Junction", "Elmsdale", 27.0);
        graphUtils.addEdge(graph, "Elmsdale", "Milford", 10.0);
        graphUtils.addEdge(graph, "Milford", "Shubenacadie", 6.0);
        graphUtils.addEdge(graph, "Shubenacadie", "Stewiacke", 7.0);
        graphUtils.addEdge(graph, "Stewiacke", "Truro", 28.0);
        graphUtils.addEdge(graph, "Truro", "Oxford Junction", 75.0);
        graphUtils.addEdge(graph, "Oxford Junction", "Springhill Junction", 21.0);
        graphUtils.addEdge(graph, "Springhill Junction", "Amherst", 28.0);
        graphUtils.addEdge(graph, "Amherst", "Sackville", 16.0);
        graphUtils.addEdge(graph, "Sackville", "Moncton", 61.0);
        graphUtils.addEdge(graph, "Moncton", "Rogersville", 93.0);
        graphUtils.addEdge(graph, "Rogersville", "Newcastle", 35.0);
        graphUtils.addEdge(graph, "Mewcastle", "Bathrust", 71.0);
        graphUtils.addEdge(graph, "Bathurst", "Jacquet River", 46.0);
        graphUtils.addEdge(graph, "Jacquet River", "Campbellton", 55.0);
        graphUtils.addEdge(graph, "Campbellton", "Matapédia", 21.0);
        graphUtils.addEdge(graph, "Matapédia", "St-Alexis", 9.0);
        graphUtils.addEdge(graph, "St-Alexis", "Ste-Florence", 36.0);
        graphUtils.addEdge(graph, "Ste-Florence", "Causapscal", 11.0);
        graphUtils.addEdge(graph, "Causapscal", "Lac-au-Saumon", 12.0);
        graphUtils.addEdge(graph, "Lac-au-Saumon", "Amqui", 9.0);
        graphUtils.addEdge(graph, "Amqui", "Val-Brilliant", 14.0);
        graphUtils.addEdge(graph, "Val-Brilliant", "Sayabec", 11.0);
        graphUtils.addEdge(graph, "Sayabec", "St-Noël", 11.0);
        graphUtils.addEdge(graph, "St-Noël", "Padoue", 13.0);
        graphUtils.addEdge(graph, "Padoue", "St-Octave", 14.0);
        graphUtils.addEdge(graph, "St-Octave", "Mont-Joli", 9.0);
        graphUtils.addEdge(graph, "Mont-Joli", "Luceville", 13.0);
        graphUtils.addEdge(graph, "Luceville", "Rimouski", 16.0);
        graphUtils.addEdge(graph, "Rimouski", "Bic", 17.0);
        graphUtils.addEdge(graph, "Bic", "St-Fabien", 15.0);
        graphUtils.addEdge(graph, "St-Fabien", "St-Simon", 16.0);
        graphUtils.addEdge(graph, "St-Simon", "Trois-Pistoles", 14.0);
        graphUtils.addEdge(graph, "Trois-Pistoles", "Isle-Verte", 17.0);
        graphUtils.addEdge(graph, "Isle-Verte", "St-Arsène", 14.0);
        graphUtils.addEdge(graph, "St-Arsène", "Rivière-du-Loup", 12.0);
        graphUtils.addEdge(graph, "Rivière-du-Loup", "Chemin-du-Lac", 10.0);
        graphUtils.addEdge(graph, "Chemin-du-Lac", "St-Alexandre", 9.0);
        graphUtils.addEdge(graph, "St-Alexandre", "Ste-Hélène", 13.0);
        graphUtils.addEdge(graph, "Ste-Hélène", "St-Pascal", 9.0);
        graphUtils.addEdge(graph, "St-Pascal", "St-Philippe-de-Néri", 10.0);
        graphUtils.addEdge(graph, "St-Philippe-de-Néri", "La Pocatière", 15.0);
        graphUtils.addEdge(graph, "La Pocatière", "St-Jean-Port-Joli", 25.0);
        graphUtils.addEdge(graph, "St-Jean-Port-Joli", "L'Islet", 13.0);
	graphUtils.addEdge(graph, "L'Islet", "Montmagny", 22.0);
	graphUtils.addEdge(graph, "Montmagny", "St-Charles", 37.0);
	graphUtils.addEdge(graph, "St-Charles", "Lévis", 22.0);
	graphUtils.addEdge(graph, "Lévis", "Charny", 13.0);
	graphUtils.addEdge(graph, "Charny", "Drummondville", 145.0); // Longest
	graphUtils.addEdge(graph, "Drummondville", "St-Hyacinthe", 47.0);
	graphUtils.addEdge(graph, "St-Hyacinthe", "St-Lambert", 47.0);
	graphUtils.addEdge(graph, "St-Lambert", "Montréal", 7.0);

	// Truro - Sydney
	graphUtils.addEdge(graph, "Truro", "Valley", 7.0);
	graphUtils.addEdge(graph, "Valley", "Union", 7.0);
	graphUtils.addEdge(graph, "Union", "Riversdale", 6.0);
	graphUtils.addEdge(graph, "Riversdale", "West River", 13.0);
	graphUtils.addEdge(graph, "West River", "Glengarry", 12.0);
	graphUtils.addEdge(graph, "Glengarry", "Lorne", 4.0);
	graphUtils.addEdge(graph, "Lorne", "Hopewell", 7.0);
	graphUtils.addEdge(graph, "Hopewwll", "Eureka", 2.0);
	graphUtils.addEdge(graph, "Eureka", "Stellarton", 7.0);
	graphUtils.addEdge(graph, "Stellarton", "New Glasgow", 4.0);
	graphUtils.addEdge(graph, "New Glasgow", "Egerton", 16.0);
	graphUtils.addEdge(graph, "Egerton", "Merigomish", 5.0);
	graphUtils.addEdge(graph, "Merigomish", "Avondale", 14.0);
	graphUtils.addEdge(graph, "Avondale", "James River", 16.0);
	graphUtils.addEdge(graph, "James River", "Antigonish", 15.0);
	graphUtils.addEdge(graph, "Antigonish", "Pomquet", 16.0);
	graphUtils.addEdge(graph, "Pomquet", "Heatherton", 4.0);
	graphUtils.addEdge(graph, "Heatherton", "Monastery", 16.0);
	graphUtils.addEdge(graph, "Monastery", "Havre Boucher", 16.0);
	graphUtils.addEdge(graph, "Havre Boucher", "Auld Cove", 12.0);
	graphUtils.addEdge(graph, "Auld Cove", "Port Hastings", 3.0);
	graphUtils.addEdge(graph, "Port Hastings", "Port Hawkesbury", 5.0);
	graphUtils.addEdge(graph, "Port Hawkesbury", "McIntyres Lake", 11.0);
	graphUtils.addEdge(graph, "McIntyres Lake", "West Bay Road", 11.0);
	graphUtils.addEdge(graph, "West Bay Road", "River Denys", 11.0);
	graphUtils.addEdge(graph, "River Denys", "Orangedale", 13.0);
	graphUtils.addEdge(graph, "Orangedale", "Alba", 8.0);
	graphUtils.addEdge(graph, "Alba", "Ottawa Brook", 6.0);
	graphUtils.addEdge(graph, "Ottawa Brook", "McKinnon Harbour", 4.0);
	graphUtils.addEdge(graph, "McKinnon Harbour", "Iona", 8.0);
	graphUtils.addEdge(graph, "Iona", "Grand Narrows", 1.0);
	graphUtils.addEdge(graph, "Grand Narrows", "Christmas Island", 5.0);
	graphUtils.addEdge(graph, "Christmas Island", "Boisdale", 23.0);
	graphUtils.addEdge(graph, "Boisdale", "Little Bras d'Or", 27.0);
	graphUtils.addEdge(graph, "Little Bras d'Or", "Sydney Mines", 6.0);
	graphUtils.addEdge(graph, "Sydney Mines", "North Sydney", 5.0);
	graphUtils.addEdge(graph, "North Sydney", "Leitches Creek", 7.0);
	graphUtils.addEdge(graph, "Leitches Creek", "Sydney", 17.0);

	// Moncton - Saint John
	graphUtils.addEdge(graph, "Moncton", "Salisbury", 21.0);
	graphUtils.addEdge(graph, "Salisbury", "River Glade", 8.0);
	graphUtils.addEdge(graph, "River Glade", "Petitcodiac", 8.0);
	graphUtils.addEdge(graph, "Petitcodiac", "Anagance", 9.0);
	graphUtils.addEdge(graph, "Anagance", "Penobsquis", 15.0);
	graphUtils.addEdge(graph, "Penobsquis", "Sussex", 12.0);
	graphUtils.addEdge(graph, "Sussex", "Apohaqui", 7.0);
	graphUtils.addEdge(graph, "Apohaqui", "Norton", 11.0);
	graphUtils.addEdge(graph, "Norton", "Bloomfield", 8.0);
	graphUtils.addEdge(graph, "Bloomfield", "Hampton", 9.0);
	graphUtils.addEdge(graph, "Hampton", "Rothesay", 21.0);
	graphUtils.addEdge(graph, "Rothesay", "Saint John", 12.0);

	// Matapédia - Gaspé
	graphUtils.addEdge(graph, "Matapédia", "Cross Point", 20.0);
	graphUtils.addEdge(graph, "Cross Point", "Nouvelle", 37.0);
	graphUtils.addEdge(graph, "Nouvelle", "Carleton", 14.0);
	graphUtils.addEdge(graph, "Carleton", "Maria", 14.0);
	graphUtils.addEdge(graph, "Maria", "Cascapédia", 12.0);
	graphUtils.addEdge(graph, "Cascapédia", "New Richmond", 14.0);
	graphUtils.addEdge(graph, "New Richmond", "Caplan", 15.0);
	graphUtils.addEdge(graph, "Caplan", "Bonaventure", 17.0);
	graphUtils.addEdge(graph, "Bonaventure", "New Carlisle", 14.0);
	graphUtils.addEdge(graph, "New Carlisle", "St-Godfroi", 18.0);
	graphUtils.addEdge(graph, "St-Godfroi", "Port-Daniel", 19.0);
	graphUtils.addEdge(graph, "Port-Daniel", "Newport", 23.0);
	graphUtils.addEdge(graph, "Newport", "Chandler", 11.0);
	graphUtils.addEdge(graph, "Chandler", "Grande-Rivière", 16.0);
	graphUtils.addEdge(graph, "Grande-Rivière", "Percé", 18.0);
	graphUtils.addEdge(graph, "Percé", "Barachois", 23.0);
	graphUtils.addEdge(graph, "Barachois", "Douglastown", 28.0);
	graphUtils.addEdge(graph, "Douglastown", "Gaspé", 12.0);

	// Montreal - Capreol
	graphUtils.addEdge(graph, "Montréal", "Dorval", 19.0);
	graphUtils.addEdge(graph, "Dorval", "Coteau", 44.0);
	graphUtils.addEdge(graph, "Coteau", "Glen Robertson", 25.0);
	graphUtils.addEdge(graph, "Glen Robertson", "Alexandria", 12.0);
	graphUtils.addEdge(graph, "Alexandria", "Maxville", 18.0);
	graphUtils.addEdge(graph, "Maxville", "Moose Creek", 10.0);
	graphUtils.addEdge(graph, "Moose Creek", "Casselman", 11.0);
	graphUtils.addEdge(graph, "Casselman", "Vars", 22.0);
	graphUtils.addEdge(graph, "Vars", "Ottawa", 26.0);
	graphUtils.addEdge(graph, "Ottawa", "Portage-du-Fort", 96.0);
	graphUtils.addEdge(graph, "Portage-du-Fort", "Pembroke", 44.0);
	graphUtils.addEdge(graph, "Pembroke", "Lake Traverse", 87.0);
	graphUtils.addEdge(graph, "Lake Traverse", "Odenback", 21.0);
	graphUtils.addEdge(graph, "Odenback", "Brent", 16.0);
	graphUtils.addEdge(graph, "Brent", "Government Park", 6.0);
	graphUtils.addEdge(graph, "Government Park", "Daventry", 10.0);
	graphUtils.addEdge(graph, "Daventry", "Kiosk", 19.0);
	graphUtils.addEdge(graph, "Kiosk", "North Bay", 74.0);
	graphUtils.addEdge(graph, "North Bay", "Field", 52.0);
	graphUtils.addEdge(graph, "Field", "Capreol", 82.0);

	// Capreol - Toronto
	graphUtils.addEdge(graph, "Capreol", "Sudbury", 22.0);
	graphUtils.addEdge(graph, "Sudbury", "Bolger", 139.0);
	graphUtils.addEdge(graph, "Bolger", "Parry Sound", 42.0);
	graphUtils.addEdge(graph, "Parry Sound", "South Parry", 4.0);
	graphUtils.addEdge(graph, "South Parry", "Washago", 94.0);
	graphUtils.addEdge(graph, "Washago", "Orillia", 20.0);
	graphUtils.addEdge(graph, "Orillia", "Barrie", 38.0);
	graphUtils.addEdge(graph, "Barrie", "Newmarket", 46.0);
	graphUtils.addEdge(graph, "Newmarket", "St Clair Avenue", 47.0);
	graphUtils.addEdge(graph, "St Clair Avenue", "Toronto", 8.0);

	// Capreol - Vancouver
	graphUtils.addEdge(graph, "Capreol", "Laforest", 49.0);
	graphUtils.addEdge(graph, "Laforest", "Westree", 55.0);
	graphUtils.addEdge(graph, "Westree", "Gogama", 35.0);
	graphUtils.addEdge(graph, "Gogama", "Foleyet", 100.0);
	graphUtils.addEdge(graph, "Foleyet", "Elsas", 56.0);
	graphUtils.addEdge(graph, "Elsas", "Oba", 120.0);
	graphUtils.addEdge(graph, "Oba", "Hornpayne", 62.0);
	graphUtils.addEdge(graph, "Hornpayne", "Hillsport", 68.0);
	graphUtils.addEdge(graph, "Hillsport", "Caramat", 57.0);
	graphUtils.addEdge(graph, "Caramat", "Longlac", 38.0);
	graphUtils.addEdge(graph, "Longlac", "Nakina", 48.0);
	graphUtils.addEdge(graph, "Nakina", "Auden", 90.0);
	graphUtils.addEdge(graph, "Auden", "Ferland", 43.0);
	graphUtils.addEdge(graph, "Ferland", "Mud River", 8.0);
	graphUtils.addEdge(graph, "Mud River", "Armstrong", 40.0);
	graphUtils.addEdge(graph, "Armstrong", "Collins", 34.0);
	graphUtils.addEdge(graph, "Collins", "Allanwater Bridge", 53.0);
	graphUtils.addEdge(graph, "Allanwater Bridge", "Savant Lake", 40.0);
	graphUtils.addEdge(graph, "Savant Lake", "Superior Junction", 86.0);
	graphUtils.addEdge(graph, "Superior Junction", "Sioux Lookout", 11.0);
	graphUtils.addEdge(graph, "Sioux Lookout", "Pelican", 10.0);
	graphUtils.addEdge(graph, "Pelican", "Hudson", 10.0);
	graphUtils.addEdge(graph, "Hudson", "Sunstrum", 31.0);
	graphUtils.addEdge(graph, "Sunstrum", "Millidge", 12.0);
	graphUtils.addEdge(graph, "Millidge", "Richan", 10.0);
	graphUtils.addEdge(graph, "Richan", "Amesdale", 8.0);
	graphUtils.addEdge(graph, "Amesdale", "Niddrie", 12.0);
	graphUtils.addEdge(graph, "Niddrie", "Morgan", 12.0);
	graphUtils.addEdge(graph, "Morgan", "Red Lake Road", 9.0);
	graphUtils.addEdge(graph, "Red Lake Road", "Quibell", 6.0);
	graphUtils.addEdge(graph, "Quibell", "McIntosh", 14.0);
	graphUtils.addEdge(graph, "McIntosh", "Canyon", 11.0);
	graphUtils.addEdge(graph, "Canyon", "Jones", 25.0);
	graphUtils.addEdge(graph, "Jones", "Farlane", 12.0);
	graphUtils.addEdge(graph, "Farlane", "Redditt", 6.0);
	graphUtils.addEdge(graph, "Redditt", "Ena Lake", 20.0);
	graphUtils.addEdge(graph, "Ena Lake", "Minaki", 13.0);
	graphUtils.addEdge(graph, "Minaki", "Wade", 10.0);
	graphUtils.addEdge(graph, "Wade", "Ottermere", 11.0);
	graphUtils.addEdge(graph, "Ottermere", "Malachi", 4.0);
	graphUtils.addEdge(graph, "Malachi", "Rice Lake", 12.0);
	graphUtils.addEdge(graph, "Rice Lake", "Winnitoba", 6.0);
	graphUtils.addEdge(graph, "Winnitoba", "Ophir", 4.0);
	graphUtils.addEdge(graph, "Ophir", "Decimal", 13.0);
	graphUtils.addEdge(graph, "Decimal", "Brereton Lake", 8.0);
	graphUtils.addEdge(graph, "Brereton Lake", "Indigo", 3.0);
	graphUtils.addEdge(graph, "Indigo", "Elma", 24.0);
	graphUtils.addEdge(graph, "Elma", "Hazel", 25.0);
	graphUtils.addEdge(graph, "Hazel", "Nourse", 8.0);
	graphUtils.addEdge(graph, "Nourse", "Vivian", 7.0);
	graphUtils.addEdge(graph, "Vivian", "Transcona", 36.0);
	graphUtils.addEdge(graph, "Transcona", "Winnipeg", 13.0);
	graphUtils.addEdge(graph, "Winnipeg", "Portage-la-Prairie", 89.0);
	graphUtils.addEdge(graph, "Portage-la-Prairie", "Brandon North", 118.0);
	graphUtils.addEdge(graph, "Brandon North", "Rivers", 24.0);
	graphUtils.addEdge(graph, "Rivers", "St Lazare", 98.0);
	graphUtils.addEdge(graph, "St Lazare", "Yarbo", 56.0);
	graphUtils.addEdge(graph, "Yarbo", "Melville", 66.0);
	graphUtils.addEdge(graph, "Melville", "Ituna", 56.0);
	graphUtils.addEdge(graph, "Ituna", "Raymore", 78.0);
	graphUtils.addEdge(graph, "Raymore", "Watrous", 74.0);
	graphUtils.addEdge(graph, "Watrous", "Saskatoon", 101.0);
	graphUtils.addEdge(graph, "Saskatoon", "Biggar", 89.0);
	graphUtils.addEdge(graph, "Biggar", "Unity", 94.0);
	graphUtils.addEdge(graph, "Unity", "Wainwright", 132.0);
	graphUtils.addEdge(graph, "Wainwright", "Viking", 71.0);
	graphUtils.addEdge(graph, "Viking", "Edmonton", 133.0);
	graphUtils.addEdge(graph, "Edmonton", "Evansburg", 109.0);
	graphUtils.addEdge(graph, "Evansburg", "Edson", 99.0);
	graphUtils.addEdge(graph, "Edson", "Hinton", 89.0);
	graphUtils.addEdge(graph, "Hinton", "Jasper", 82.0);
	graphUtils.addEdge(graph, "Jasper", "Red Pass Junction", 69.0);
	graphUtils.addEdge(graph, "Red Pass Junction", "Valemount", 51.0);
	graphUtils.addEdge(graph, "Valemount", "Blue River", 93.0);
	graphUtils.addEdge(graph, "Blue River", "Avola", 40.0);
	graphUtils.addEdge(graph, "Avola", "Vavenby", 45.0);
	graphUtils.addEdge(graph, "Vavenby", "Clearwater", 24.0);
	graphUtils.addEdge(graph, "Clearwater", "Kamloops Junction", 115.0);
	graphUtils.addEdge(graph, "Kamloops Junction", "Ashcroft", 79.0);
	graphUtils.addEdge(graph, "Ashcroft", "Lytton", 78.0);
	graphUtils.addEdge(graph, "Lytton", "Boston Bar", 45.0);
	graphUtils.addEdge(graph, "Boston Bar", "Hope", 65.0);
	graphUtils.addEdge(graph, "Hope", "Chilliwack", 51.0);
	graphUtils.addEdge(graph, "Chilliwack", "Matsqui", 25.0);
	graphUtils.addEdge(graph, "Matsqui", "Fort Langley", 25.0);
	graphUtils.addEdge(graph, "Fort Langley", "New Westminster", 27.0);
	graphUtils.addEdge(graph, "New Westminster", "Vancouver", 19.0);

		// Red Pass Junction - Prince Rupert TODO
	graphUtils.addEdge(graph, "Red Pass Junction", "Tête-Jaune", 40.0);
	graphUtils.addEdge(graph, "Tête-Jaune", "Croydon", 20.0);
	graphUtils.addEdge(graph, "Croydon", "Dunster", 10.0);
	graphUtils.addEdge(graph, "Dunster", "McBride", 32.0);
	graphUtils.addEdge(graph, "McBride", "Legrand", 21.0);
	graphUtils.addEdge(graph, "Lagrand", "Goat River", 24.0);
	graphUtils.addEdge(graph, "Goat River", "Crescent Spur", 10.0);
	graphUtils.addEdge(graph, "Screscent Spur", "Loos", 3.0);
	graphUtils.addEdge(graph, "Loos", "Rock Pit", 18.0);
	graphUtils.addEdge(graph, "Rock Pit", "Kidd", 8.0);
	graphUtils.addEdge(graph, "Kidd", "Dome Creek", 6.0);
	graphUtils.addEdge(graph, "Dome Creek", "Bend", 3.0);
	graphUtils.addEdge(graph, "Bend", "Penny", 19.0);
	graphUtils.addEdge(graph, "Penny", "Longworth", 16.0);
	graphUtils.addEdge(graph, "Longworth", "Hutton", 13.0);
	graphUtils.addEdge(graph, "Hutton", "Sinclair Mills", 5.0);
	graphUtils.addEdge(graph, "Sinclair Mills", "McGregor", 12.0);
	graphUtils.addEdge(graph, "McGregor", "Hansard", 3.0);
	graphUtils.addEdge(graph, "Hansard", "Upper Fraser", 6.0);
	graphUtils.addEdge(graph, "Upper Fraser", "Aleza Lake", 8.0);
	graphUtils.addEdge(graph, "Aleza Lake", "Giscome", 22.0);
	graphUtils.addEdge(graph, "Giscome", "Willow River", 7.0);
	graphUtils.addEdge(graph, "Willow River", "Shelley", 15.0);
	graphUtils.addEdge(graph, "Shelley", "Prince George", 16.0);
	graphUtils.addEdge(graph, "Prince George", "Vanderhoof", 112.0);
	graphUtils.addEdge(graph, "Vanderhoof", "Engen", 21.0);
	graphUtils.addEdge(graph, "Engen", "Fort Fraser", 19.0);
	graphUtils.addEdge(graph, "Fort Fraser", "Lejac", 15.0);
	graphUtils.addEdge(graph, "Lejac", "Endako", 19.0);
	graphUtils.addEdge(graph, "Endako", "Burns Lake", 56.0);
	graphUtils.addEdge(graph, "Burns Lake", "Houston", 83.0);
	graphUtils.addEdge(graph, "Houston", "Telkwa", 48.0);
	graphUtils.addEdge(graph, "Telkwa", "Smithers", 14.0);
	graphUtils.addEdge(graph, "Smithers", "New Hazelton", 74.0);
	graphUtils.addEdge(graph, "New Hazelton", "Skeena Crossing", 26.0);

        return graph;
    }
}
